export const CREATE_MERCHANT = 'CREATE_MERCHANT';
export const CREATE_MERCHANT_SUCCESS = 'CREATE_MERCHANT_SUCCESS';
export const CREATE_MERCHANT_FAILURE = 'CREATE_MERCHANT_FAILURE';
export const WILL_FETCH_MERCHANTS = 'FETCH_MERCHANTS';
export const FETCH_MERCHANTS_SUCCESS = 'FETCH_MERCHANTS_SUCCESS';
export const FETCH_MERCHANTS_FAILURE = 'FETCH_MERCHANTS_FAILURE';
